# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MemoModel
                                 A QGIS plugin
 用於評估地下水監測井網路效率的套件
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-30
        copyright            : (C) 2026 by RayTai
        email                : rationtai@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MemoModel class from file MemoModel.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MemoModel import MemoModel
    return MemoModel(iface)
