# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MemoModel
                                 A QGIS plugin
 用於評估地下水監測井網路效率的套件
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by RayTai
        email                : rationtai@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .MemoModel_dialog import MemoModelDialog
import os.path


class MemoModel:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'MemoModel_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&MEMO Groundwater Network Design')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('MemoModel', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        # 這是原本的寫法（通常需要編譯資源檔）
        # icon_path = ':/plugins/MEMO_Plugin/icon.png'

        # 【偷吃步寫法】直接讓程式抓取外掛資料夾底下的 icon.png
        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u''),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&MEMO Groundwater Network Design'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """當使用者按下執行按鈕時，會跑來這裡"""
        
        # 1. 讓視窗顯示出來 (Plugin Builder 預設會有的程式碼)
        if self.first_start == True:
            self.first_start = False
            self.dlg = MemoModelDialog()
            
            # 【按鈕綁定區】
            # 將介面上的 btnRun 按鈕，綁定到 calculate_memo 函數 (執行模擬)
            self.dlg.btnRun.clicked.connect(self.calculate_memo)
            
            # 將介面上的 btnHelp 按鈕，綁定到 show_help 函數 (顯示說明書)
            # ⚠️ 注意：請確保你在 Qt Designer 裡有新增這個按鈕，並且命名為 btnHelp
            self.dlg.btnHelp.clicked.connect(self.show_help)

        # 2. 顯示對話框
        self.dlg.show()
        result = self.dlg.exec_()
        if result:
            pass

    def show_help(self):
        """讀取並在具備捲軸的視窗中顯示 help.txt 說明檔"""
        import os
        from qgis.PyQt.QtWidgets import QMessageBox, QDialog, QVBoxLayout, QTextEdit, QPushButton
        from qgis.PyQt.QtGui import QFont
        
        # 取得目前這個 Python 檔案所在的資料夾路徑，並尋找 help.txt
        plugin_dir = os.path.dirname(__file__)
        help_path = os.path.join(plugin_dir, 'help.txt')
        
        try:
            # 讀取文字檔 (強制使用 utf-8 避免中文亂碼)
            with open(help_path, 'r', encoding='utf-8') as f:
                help_text = f.read()
                
            # ===============================================
            # 建立專業的獨立捲軸視窗 (QDialog)
            # ===============================================
            help_dialog = QDialog(self.dlg)
            help_dialog.setWindowTitle("MEMO 參數設定與操作說明")
            help_dialog.resize(600, 500)  # 設定視窗預設大小 (寬 600, 高 500)
            
            # 建立垂直排版配置 (讓文字在上面，按鈕在下面)
            layout = QVBoxLayout()
            
            # 建立文字顯示區 (具備自動捲軸功能)
            text_box = QTextEdit()
            text_box.setReadOnly(True)  # 設定為唯讀，避免使用者不小心改到文字
            text_box.setPlainText(help_text)
            
            # (加分項) 設定字體微調，讓 txt 的排版更整齊易讀
            font = QFont("Microsoft JhengHei", 10) # 使用微軟正黑體，大小 10
            text_box.setFont(font)
            
            # 建立一個大大的「關閉」按鈕
            btn_close = QPushButton("關閉說明")
            btn_close.clicked.connect(help_dialog.accept)
            
            # 將文字區和按鈕依序放入排版配置中
            layout.addWidget(text_box)
            layout.addWidget(btn_close)
            help_dialog.setLayout(layout)
            
            # 顯示這個華麗的新視窗！
            help_dialog.exec_()
            
        except Exception as e:
            QMessageBox.warning(self.dlg, "找不到說明檔", f"無法開啟說明文件！\n請確認 help.txt 是否放在外掛資料夾中。\n錯誤訊息：{e}")
            

    def calculate_memo(self):
        """讀取參數執行模擬，支援動態網格尺寸，並一鍵匯出 GPKG (含樣式) 與雙語報告"""
        from qgis.core import (QgsPointXY, QgsGeometry, QgsProject, QgsWkbTypes,
                               QgsVectorLayer, QgsField, QgsFeature, QgsSymbol,
                               QgsCategorizedSymbolRenderer, QgsRendererCategory,
                               QgsSingleSymbolRenderer, QgsMarkerSymbol, 
                               QgsRectangle, QgsFillSymbol, QgsVectorFileWriter, QgsUnitTypes)
        from qgis.PyQt.QtWidgets import QMessageBox, QFileDialog 
        from qgis.PyQt.QtCore import QVariant
        from qgis.PyQt.QtGui import QColor
        import math, os

        # 1. 讀取 UI 設定與防呆
        source_layer = self.dlg.combo_SourceLayer.currentLayer()
        well_layer = self.dlg.combo_WellLayer.currentLayer()
        
        if not source_layer or not well_layer:
            QMessageBox.warning(self.dlg, "錯誤", "請確保已正確選擇「污染源」與「監測井」圖層！")
            return

        if well_layer.geometryType() != QgsWkbTypes.PointGeometry:
            QMessageBox.warning(self.dlg, "圖層選錯啦", "「監測井圖層」必須是點 (Point) 圖層！")
            return

        well_points = [f.geometry().asPoint() for f in well_layer.getFeatures()]
        if not well_points:
            QMessageBox.warning(self.dlg, "錯誤", "選定的監測井圖層中沒有點位資料！")
            return

        source_crs = source_layer.crs()
        if source_crs.isGeographic():
            QMessageBox.critical(self.dlg, "座標系統錯誤", "請使用投影座標系 (例如 TWD97 EPSG:3826)！")
            return
        if source_crs.mapUnits() != QgsUnitTypes.DistanceMeters:
            QMessageBox.critical(self.dlg, "單位錯誤", "該圖層的座標單位不是「公尺」！")
            return

        # 2. 動態讀取參數 (包含全新的動態網格尺寸)
        try:
            l_disp = self.dlg.spin_LDisp.value()
            t_disp = self.dlg.spin_TDisp.value()
            v = self.dlg.spin_V.value()
            Y = self.dlg.spin_Y.value()
            t = self.dlg.spin_Time.value()
            C_dil = self.dlg.spin_CDil.value()
            angle_deg = self.dlg.spin_Angle.value()
            angle_rad = math.radians(angle_deg)
            cos_a, sin_a = math.cos(angle_rad), math.sin(angle_rad)
            
            # 【新增】動態讀取網格尺寸
            grid_spacing = self.dlg.spin_GridSize.value()
        except AttributeError as e:
            # 防呆機制：如果找不到 spin_GridSize，就自動用 25 公尺，並印出提示
            # 這樣不會因為 UI 沒設定好就當機
            print(f"UI 讀取警告：{e}。將使用預設網格間距 25m。")
            grid_spacing = 25.0

        Dx = l_disp * v
        Dy = t_disp * v

        # 3. Domenico 核心運算引擎
        def domenico_concentration(x, y):
            if x <= 0: return 0.0 
            try:
                term1 = math.erfc((x - v * t) / (2 * math.sqrt(Dx * t)))
                term2 = math.erf((y + Y / 2) / (2 * math.sqrt(Dy * x / v)))
                term3 = math.erf((y - Y / 2) / (2 * math.sqrt(Dy * x / v)))
                return 0.25 * term1 * (term2 - term3)
            except: return 0.0

        # 4. 執行模擬運算
        half_grid = grid_spacing / 2.0  # 【修正】根據使用者定義的網格動態計算多邊形半徑
        total_points, detected_count = 0, 0
        result_features, missed_polygons = [], [] 

        for feature in source_layer.getFeatures():
            geom, bbox = feature.geometry(), feature.geometry().boundingBox()
            x_src = bbox.xMinimum()
            while x_src <= bbox.xMaximum():
                y_src = bbox.yMinimum()
                while y_src <= bbox.yMaximum():
                    pt_geom = QgsGeometry.fromPointXY(QgsPointXY(x_src, y_src))
                    if geom.contains(pt_geom):
                        total_points += 1
                        is_detected = False
                        for wp in well_points:
                            if domenico_concentration((wp.x()-x_src)*cos_a + (wp.y()-y_src)*sin_a, 
                                                    -(wp.x()-x_src)*sin_a + (wp.y()-y_src)*cos_a) >= C_dil:
                                is_detected = True; break
                        feat = QgsFeature(); feat.setGeometry(pt_geom)
                        if is_detected:
                            detected_count += 1; feat.setAttributes(["Detected"])
                        else:
                            feat.setAttributes(["Missed"])
                            # 【修正】使用動態半徑畫盲區正方形
                            rect = QgsRectangle(x_src - half_grid, y_src - half_grid, x_src + half_grid, y_src + half_grid)
                            missed_polygons.append(QgsGeometry.fromRect(rect))
                        result_features.append(feat)
                    y_src += grid_spacing
                x_src += grid_spacing

        # 5. 生成暫存圖層並設定樣式
        if total_points > 0:
            efficiency = (detected_count / total_points) * 100
            crs_id = source_layer.crs().authid()
            layers_to_export = [] 

            # 清除舊的暫存圖層
            layer_names_to_remove = ["MEMO_流向箭頭", "MEMO_盲區範圍多邊形", "MEMO_網格點分析結果"]
            for name in layer_names_to_remove:
                for old_layer in QgsProject.instance().mapLayersByName(name):
                    QgsProject.instance().removeMapLayer(old_layer)

            # A. 建立流向箭頭圖層
            arrow_layer_name = "MEMO_流向箭頭"
            center_pt = source_layer.extent().center()
            center_feat = QgsFeature()
            center_feat.setGeometry(QgsGeometry.fromPointXY(center_pt))
            arrow_layer = QgsVectorLayer(f"Point?crs={crs_id}", arrow_layer_name, "memory")
            arrow_layer.dataProvider().addFeatures([center_feat])
            symbol = QgsMarkerSymbol.createSimple({'name': 'arrow', 'color': 'grey', 'size': '12', 'outline_color': 'grey'})
            symbol.setAngle(90.0 - angle_deg) 
            arrow_layer.setRenderer(QgsSingleSymbolRenderer(symbol))
            QgsProject.instance().addMapLayer(arrow_layer)
            layers_to_export.append(arrow_layer)

            # B. 建立盲區多邊形
            blind_layer = None
            blind_area_sqm = 0
            if missed_polygons:
                blind_layer = QgsVectorLayer(f"Polygon?crs={crs_id}", "MEMO_盲區範圍多邊形", "memory")
                blind_pr = blind_layer.dataProvider()
                blind_pr.addAttributes([QgsField("Area_sqm", QVariant.Double)])
                blind_layer.updateFields()
                merged_geom = QgsGeometry.unaryUnion(missed_polygons)
                blind_area_sqm = merged_geom.area()
                bf = QgsFeature(); bf.setGeometry(merged_geom); bf.setAttributes([blind_area_sqm])
                blind_pr.addFeatures([bf])
                blind_layer.setRenderer(QgsSingleSymbolRenderer(QgsFillSymbol.createSimple({'color': '255,0,0,100', 'outline_color': '255,0,0,255'})))
                QgsProject.instance().addMapLayer(blind_layer)
                layers_to_export.append(blind_layer)

            # C. 建立網格點
            res_layer = QgsVectorLayer(f"Point?crs={crs_id}", "MEMO_網格點分析結果", "memory")
            res_pr = res_layer.dataProvider()
            res_pr.addAttributes([QgsField("Status", QVariant.String)])
            res_layer.updateFields(); res_pr.addFeatures(result_features)
            categories = [
                QgsRendererCategory("Detected", QgsMarkerSymbol.createSimple({'color': '0,200,0', 'size': '2'}), "成功偵測", True),
                QgsRendererCategory("Missed", QgsMarkerSymbol.createSimple({'color': '255,0,0', 'size': '2'}), "未偵測", True)
            ]
            res_layer.setRenderer(QgsCategorizedSymbolRenderer("Status", categories))
            QgsProject.instance().addMapLayer(res_layer)
            layers_to_export.append(res_layer)

            # 6. 彈出演示視窗並詢問是否保存
            msg = f"模擬完成！\n網格尺寸: {grid_spacing}m x {grid_spacing}m\n監測效率: {efficiency:.1f}%\n盲區面積: {blind_area_sqm:,.1f} m2\n\n是否確定要將此次模擬結果匯出成 GPKG 專案包與參數報告？"
            if QMessageBox.question(self.dlg, "模擬成功", msg, QMessageBox.Yes | QMessageBox.No) == QMessageBox.Yes:
                
                # 7. 一鍵匯出流程
                file_path, _ = QFileDialog.getSaveFileName(self.dlg, "匯出專案包", "MEMO_Simulation_Project.gpkg", "GeoPackage (*.gpkg)")
                if file_path:
                    try:
                        save_options = QgsVectorFileWriter.SaveVectorOptions()
                        save_options.driverName = "GPKG"
                        
                        for i, lyr in enumerate(layers_to_export):
                            save_options.layerName = lyr.name()
                            if i == 0:
                                save_options.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteFile
                            else:
                                save_options.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteLayer
                                
                            QgsVectorFileWriter.writeAsVectorFormatV3(lyr, file_path, QgsProject.instance().transformContext(), save_options)
                            
                            qml_path = os.path.join(os.path.dirname(file_path), f"{lyr.name()}.qml")
                            lyr.saveNamedStyle(qml_path)

                        # 產出更新版的雙語報告
                        report_path = os.path.splitext(file_path)[0] + "_Summary.txt"
                        with open(report_path, 'w', encoding='utf-8') as f:
                            f.write("=========================================================\n")
                            f.write("      MEMO 監測井網模擬摘要報告 / Simulation Summary      \n")
                            f.write("=========================================================\n\n")

                            f.write("[ 模擬參數 / Simulation Parameters ]\n")
                            f.write(f"- 網格解析度 / Grid Size : {grid_spacing} m\n") # 【新增】記錄網格大小
                            f.write(f"- 地下水流向角度 / Groundwater Flow Angle : {angle_deg} °\n")
                            f.write(f"- 縱向擴散係數 / Longitudinal Dispersivity (L_disp) : {l_disp} m\n")
                            f.write(f"- 橫向擴散係數 / Transverse Dispersivity (T_disp) : {t_disp} m\n")
                            f.write(f"- 平均污染流速 / Average Contaminant Velocity (v) : {v} m/day\n")
                            f.write(f"- 污染源寬度 / Source Width (Y) : {Y} m\n")
                            f.write(f"- 模擬時間 / Advection Time (t) : {t} days\n")
                            f.write(f"- 稀釋等高線標準 / Dilution Contour (C_dil) : {C_dil}\n\n")

                            f.write("[ 模擬結果 / Simulation Results ]\n")
                            f.write(f"- 總網格點數 / Total Grid Points : {total_points}\n")
                            f.write(f"- 成功偵測點數 / Detected Points : {detected_count}\n")
                            f.write(f"- 監測效率 / Monitoring Efficiency : {efficiency:.1f} %\n")
                            f.write(f"- 盲區總面積 / Total Blind Area : {blind_area_sqm:,.1f} sq. meters\n")

                        QMessageBox.information(self.dlg, "匯出完成", f"已成功保存：\n1. GPKG 空間資料庫\n2. QML 樣式檔\n3. 雙語摘要報告 (.txt)\n\n檔案已存至：{os.path.dirname(file_path)}")
                    except Exception as e:
                        QMessageBox.critical(self.dlg, "匯出失敗", f"發生不可預期的錯誤：{e}")
        else:
            QMessageBox.warning(self.dlg, "無效的網格", "未產生任何網格點，請檢查圖層與範圍！")